/*
 * Billsby API
 * Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..
 *
 * The version of the OpenAPI document: 1.3.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AllowanceGetDetailsResponseCounter;
import com.konfigthis.client.model.AllowanceGetDetailsResponsePlansInner;
import com.konfigthis.client.model.AllowanceGetDetailsResponsePriceModelsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AllowanceGetDetailsResponse
 */
public class AllowanceGetDetailsResponseTest {
    private final AllowanceGetDetailsResponse model = new AllowanceGetDetailsResponse();

    /**
     * Model tests for AllowanceGetDetailsResponse
     */
    @Test
    public void testAllowanceGetDetailsResponse() {
        // TODO: test AllowanceGetDetailsResponse
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'allowanceId'
     */
    @Test
    public void allowanceIdTest() {
        // TODO: test allowanceId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'singleUnitName'
     */
    @Test
    public void singleUnitNameTest() {
        // TODO: test singleUnitName
    }

    /**
     * Test the property 'pluralUnitName'
     */
    @Test
    public void pluralUnitNameTest() {
        // TODO: test pluralUnitName
    }

    /**
     * Test the property 'pricingModelType'
     */
    @Test
    public void pricingModelTypeTest() {
        // TODO: test pricingModelType
    }

    /**
     * Test the property 'counter'
     */
    @Test
    public void counterTest() {
        // TODO: test counter
    }

    /**
     * Test the property 'hasActiveLinkedPlans'
     */
    @Test
    public void hasActiveLinkedPlansTest() {
        // TODO: test hasActiveLinkedPlans
    }

    /**
     * Test the property 'featureTags'
     */
    @Test
    public void featureTagsTest() {
        // TODO: test featureTags
    }

    /**
     * Test the property 'plans'
     */
    @Test
    public void plansTest() {
        // TODO: test plans
    }

    /**
     * Test the property 'priceModels'
     */
    @Test
    public void priceModelsTest() {
        // TODO: test priceModels
    }

}
