/*
 * Billsby API
 * Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..
 *
 * The version of the OpenAPI document: 1.3.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InvoiceDetailsResponseSubscriptionsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InvoiceDetailsResponse
 */
public class InvoiceDetailsResponseTest {
    private final InvoiceDetailsResponse model = new InvoiceDetailsResponse();

    /**
     * Model tests for InvoiceDetailsResponse
     */
    @Test
    public void testInvoiceDetailsResponse() {
        // TODO: test InvoiceDetailsResponse
    }

    /**
     * Test the property 'invoiceId'
     */
    @Test
    public void invoiceIdTest() {
        // TODO: test invoiceId
    }

    /**
     * Test the property 'customerEmail'
     */
    @Test
    public void customerEmailTest() {
        // TODO: test customerEmail
    }

    /**
     * Test the property 'customerFirstName'
     */
    @Test
    public void customerFirstNameTest() {
        // TODO: test customerFirstName
    }

    /**
     * Test the property 'customerLastName'
     */
    @Test
    public void customerLastNameTest() {
        // TODO: test customerLastName
    }

    /**
     * Test the property 'customerUniqueId'
     */
    @Test
    public void customerUniqueIdTest() {
        // TODO: test customerUniqueId
    }

    /**
     * Test the property 'addressLine1'
     */
    @Test
    public void addressLine1Test() {
        // TODO: test addressLine1
    }

    /**
     * Test the property 'addressLine2'
     */
    @Test
    public void addressLine2Test() {
        // TODO: test addressLine2
    }

    /**
     * Test the property 'addressPostCode'
     */
    @Test
    public void addressPostCodeTest() {
        // TODO: test addressPostCode
    }

    /**
     * Test the property 'addressCity'
     */
    @Test
    public void addressCityTest() {
        // TODO: test addressCity
    }

    /**
     * Test the property 'addressState'
     */
    @Test
    public void addressStateTest() {
        // TODO: test addressState
    }

    /**
     * Test the property 'addressCountry'
     */
    @Test
    public void addressCountryTest() {
        // TODO: test addressCountry
    }

    /**
     * Test the property 'addressCountryCode'
     */
    @Test
    public void addressCountryCodeTest() {
        // TODO: test addressCountryCode
    }

    /**
     * Test the property 'invoiceNumber'
     */
    @Test
    public void invoiceNumberTest() {
        // TODO: test invoiceNumber
    }

    /**
     * Test the property 'createdOn'
     */
    @Test
    public void createdOnTest() {
        // TODO: test createdOn
    }

    /**
     * Test the property 'formattedAmount'
     */
    @Test
    public void formattedAmountTest() {
        // TODO: test formattedAmount
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'subTotal'
     */
    @Test
    public void subTotalTest() {
        // TODO: test subTotal
    }

    /**
     * Test the property 'taxTotal'
     */
    @Test
    public void taxTotalTest() {
        // TODO: test taxTotal
    }

    /**
     * Test the property 'prorationAdjustment'
     */
    @Test
    public void prorationAdjustmentTest() {
        // TODO: test prorationAdjustment
    }

    /**
     * Test the property 'prorationFactor'
     */
    @Test
    public void prorationFactorTest() {
        // TODO: test prorationFactor
    }

    /**
     * Test the property 'taxes'
     */
    @Test
    public void taxesTest() {
        // TODO: test taxes
    }

    /**
     * Test the property 'invoiceType'
     */
    @Test
    public void invoiceTypeTest() {
        // TODO: test invoiceType
    }

    /**
     * Test the property 'subscriptions'
     */
    @Test
    public void subscriptionsTest() {
        // TODO: test subscriptions
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'companyEmail'
     */
    @Test
    public void companyEmailTest() {
        // TODO: test companyEmail
    }

    /**
     * Test the property 'companyTaxNumber'
     */
    @Test
    public void companyTaxNumberTest() {
        // TODO: test companyTaxNumber
    }

    /**
     * Test the property 'companyDomain'
     */
    @Test
    public void companyDomainTest() {
        // TODO: test companyDomain
    }

    /**
     * Test the property 'companyPhoneNumberDialCountry'
     */
    @Test
    public void companyPhoneNumberDialCountryTest() {
        // TODO: test companyPhoneNumberDialCountry
    }

    /**
     * Test the property 'companyPhoneNumberDialCode'
     */
    @Test
    public void companyPhoneNumberDialCodeTest() {
        // TODO: test companyPhoneNumberDialCode
    }

    /**
     * Test the property 'companyPhoneNumber'
     */
    @Test
    public void companyPhoneNumberTest() {
        // TODO: test companyPhoneNumber
    }

    /**
     * Test the property 'companyAddressLine1'
     */
    @Test
    public void companyAddressLine1Test() {
        // TODO: test companyAddressLine1
    }

    /**
     * Test the property 'companyAddressLine2'
     */
    @Test
    public void companyAddressLine2Test() {
        // TODO: test companyAddressLine2
    }

    /**
     * Test the property 'companyCity'
     */
    @Test
    public void companyCityTest() {
        // TODO: test companyCity
    }

    /**
     * Test the property 'companyState'
     */
    @Test
    public void companyStateTest() {
        // TODO: test companyState
    }

    /**
     * Test the property 'companyPostCode'
     */
    @Test
    public void companyPostCodeTest() {
        // TODO: test companyPostCode
    }

    /**
     * Test the property 'companyCountry'
     */
    @Test
    public void companyCountryTest() {
        // TODO: test companyCountry
    }

    /**
     * Test the property 'brandingLogo'
     */
    @Test
    public void brandingLogoTest() {
        // TODO: test brandingLogo
    }

    /**
     * Test the property 'brandingLogoBackgroundColor'
     */
    @Test
    public void brandingLogoBackgroundColorTest() {
        // TODO: test brandingLogoBackgroundColor
    }

    /**
     * Test the property 'brandingHighlightColor'
     */
    @Test
    public void brandingHighlightColorTest() {
        // TODO: test brandingHighlightColor
    }

    /**
     * Test the property 'supportUrl'
     */
    @Test
    public void supportUrlTest() {
        // TODO: test supportUrl
    }

    /**
     * Test the property 'cardType'
     */
    @Test
    public void cardTypeTest() {
        // TODO: test cardType
    }

    /**
     * Test the property 'cardLast4Digits'
     */
    @Test
    public void cardLast4DigitsTest() {
        // TODO: test cardLast4Digits
    }

    /**
     * Test the property 'cardExpiryMonth'
     */
    @Test
    public void cardExpiryMonthTest() {
        // TODO: test cardExpiryMonth
    }

    /**
     * Test the property 'cardExpiryYear'
     */
    @Test
    public void cardExpiryYearTest() {
        // TODO: test cardExpiryYear
    }

    /**
     * Test the property 'refundableAmount'
     */
    @Test
    public void refundableAmountTest() {
        // TODO: test refundableAmount
    }

    /**
     * Test the property 'footerCompanyName'
     */
    @Test
    public void footerCompanyNameTest() {
        // TODO: test footerCompanyName
    }

    /**
     * Test the property 'footerAddressLine1'
     */
    @Test
    public void footerAddressLine1Test() {
        // TODO: test footerAddressLine1
    }

    /**
     * Test the property 'footerAddressLine2'
     */
    @Test
    public void footerAddressLine2Test() {
        // TODO: test footerAddressLine2
    }

    /**
     * Test the property 'footerAddressState'
     */
    @Test
    public void footerAddressStateTest() {
        // TODO: test footerAddressState
    }

    /**
     * Test the property 'footerAddressCity'
     */
    @Test
    public void footerAddressCityTest() {
        // TODO: test footerAddressCity
    }

    /**
     * Test the property 'footerAddressPostCode'
     */
    @Test
    public void footerAddressPostCodeTest() {
        // TODO: test footerAddressPostCode
    }

    /**
     * Test the property 'footerAddressCountryISO3'
     */
    @Test
    public void footerAddressCountryISO3Test() {
        // TODO: test footerAddressCountryISO3
    }

    /**
     * Test the property 'footerEmailAddress'
     */
    @Test
    public void footerEmailAddressTest() {
        // TODO: test footerEmailAddress
    }

    /**
     * Test the property 'footerPhoneNumberDialCountry'
     */
    @Test
    public void footerPhoneNumberDialCountryTest() {
        // TODO: test footerPhoneNumberDialCountry
    }

    /**
     * Test the property 'footerPhoneNumberDialCode'
     */
    @Test
    public void footerPhoneNumberDialCodeTest() {
        // TODO: test footerPhoneNumberDialCode
    }

    /**
     * Test the property 'footerPhoneNumber'
     */
    @Test
    public void footerPhoneNumberTest() {
        // TODO: test footerPhoneNumber
    }

    /**
     * Test the property 'supportContactHeading'
     */
    @Test
    public void supportContactHeadingTest() {
        // TODO: test supportContactHeading
    }

    /**
     * Test the property 'supportContactContent'
     */
    @Test
    public void supportContactContentTest() {
        // TODO: test supportContactContent
    }

    /**
     * Test the property 'supportContactSupportUrl'
     */
    @Test
    public void supportContactSupportUrlTest() {
        // TODO: test supportContactSupportUrl
    }

    /**
     * Test the property 'supportContactSupportUrlButtonText'
     */
    @Test
    public void supportContactSupportUrlButtonTextTest() {
        // TODO: test supportContactSupportUrlButtonText
    }

    /**
     * Test the property 'isAdvertEnabled'
     */
    @Test
    public void isAdvertEnabledTest() {
        // TODO: test isAdvertEnabled
    }

    /**
     * Test the property 'advertImageUrl'
     */
    @Test
    public void advertImageUrlTest() {
        // TODO: test advertImageUrl
    }

    /**
     * Test the property 'advertLinkToUrl'
     */
    @Test
    public void advertLinkToUrlTest() {
        // TODO: test advertLinkToUrl
    }

}
