/*
 * Billsby API
 * Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..
 *
 * The version of the OpenAPI document: 1.3.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ProductUpdateProductRequestOrderedCustomFields;
import com.konfigthis.client.model.ProductUpdateProductRequestProductCountryLimitations;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductCreateNewProductRequest
 */
public class ProductCreateNewProductRequestTest {
    private final ProductCreateNewProductRequest model = new ProductCreateNewProductRequest();

    /**
     * Model tests for ProductCreateNewProductRequest
     */
    @Test
    public void testProductCreateNewProductRequest() {
        // TODO: test ProductCreateNewProductRequest
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'visibility'
     */
    @Test
    public void visibilityTest() {
        // TODO: test visibility
    }

    /**
     * Test the property 'billingCurrency'
     */
    @Test
    public void billingCurrencyTest() {
        // TODO: test billingCurrency
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'isShippingAddressRequired'
     */
    @Test
    public void isShippingAddressRequiredTest() {
        // TODO: test isShippingAddressRequired
    }

    /**
     * Test the property 'isShippingAddressValidationRequired'
     */
    @Test
    public void isShippingAddressValidationRequiredTest() {
        // TODO: test isShippingAddressValidationRequired
    }

    /**
     * Test the property 'isBillingAddressValidationRequired'
     */
    @Test
    public void isBillingAddressValidationRequiredTest() {
        // TODO: test isBillingAddressValidationRequired
    }

    /**
     * Test the property 'isAdditionalEmailRequired'
     */
    @Test
    public void isAdditionalEmailRequiredTest() {
        // TODO: test isAdditionalEmailRequired
    }

    /**
     * Test the property 'isPhoneNumberRequired'
     */
    @Test
    public void isPhoneNumberRequiredTest() {
        // TODO: test isPhoneNumberRequired
    }

    /**
     * Test the property 'isMarketingConsentRequired'
     */
    @Test
    public void isMarketingConsentRequiredTest() {
        // TODO: test isMarketingConsentRequired
    }

    /**
     * Test the property 'alertEmail'
     */
    @Test
    public void alertEmailTest() {
        // TODO: test alertEmail
    }

    /**
     * Test the property 'orderedCustomFields'
     */
    @Test
    public void orderedCustomFieldsTest() {
        // TODO: test orderedCustomFields
    }

    /**
     * Test the property 'typeOfProduct'
     */
    @Test
    public void typeOfProductTest() {
        // TODO: test typeOfProduct
    }

    /**
     * Test the property 'productCountryLimitation'
     */
    @Test
    public void productCountryLimitationTest() {
        // TODO: test productCountryLimitation
    }

    /**
     * Test the property 'isAnyCountryAllowed'
     */
    @Test
    public void isAnyCountryAllowedTest() {
        // TODO: test isAnyCountryAllowed
    }

}
