/*
 * Billsby API
 * Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..
 *
 * The version of the OpenAPI document: 1.3.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ProductCreateCycleRequestCyclesInputModelInnerTiersInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProductCreateCycleRequestAllowancePlanInputModelInnerAllowancePriceModelsInner
 */
public class ProductCreateCycleRequestAllowancePlanInputModelInnerAllowancePriceModelsInnerTest {
    private final ProductCreateCycleRequestAllowancePlanInputModelInnerAllowancePriceModelsInner model = new ProductCreateCycleRequestAllowancePlanInputModelInnerAllowancePriceModelsInner();

    /**
     * Model tests for ProductCreateCycleRequestAllowancePlanInputModelInnerAllowancePriceModelsInner
     */
    @Test
    public void testProductCreateCycleRequestAllowancePlanInputModelInnerAllowancePriceModelsInner() {
        // TODO: test ProductCreateCycleRequestAllowancePlanInputModelInnerAllowancePriceModelsInner
    }

    /**
     * Test the property 'currencyIso3Code'
     */
    @Test
    public void currencyIso3CodeTest() {
        // TODO: test currencyIso3Code
    }

    /**
     * Test the property 'frequency'
     */
    @Test
    public void frequencyTest() {
        // TODO: test frequency
    }

    /**
     * Test the property 'frequencyType'
     */
    @Test
    public void frequencyTypeTest() {
        // TODO: test frequencyType
    }

    /**
     * Test the property 'includedUnits'
     */
    @Test
    public void includedUnitsTest() {
        // TODO: test includedUnits
    }

    /**
     * Test the property 'pricePerUnit'
     */
    @Test
    public void pricePerUnitTest() {
        // TODO: test pricePerUnit
    }

    /**
     * Test the property 'unitTiers'
     */
    @Test
    public void unitTiersTest() {
        // TODO: test unitTiers
    }

}
