/*
 * Billsby API
 * Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..
 *
 * The version of the OpenAPI document: 1.3.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SubscriptionListSubscriptionsResponseResultsInner
 */
public class SubscriptionListSubscriptionsResponseResultsInnerTest {
    private final SubscriptionListSubscriptionsResponseResultsInner model = new SubscriptionListSubscriptionsResponseResultsInner();

    /**
     * Model tests for SubscriptionListSubscriptionsResponseResultsInner
     */
    @Test
    public void testSubscriptionListSubscriptionsResponseResultsInner() {
        // TODO: test SubscriptionListSubscriptionsResponseResultsInner
    }

    /**
     * Test the property 'subscriptionId'
     */
    @Test
    public void subscriptionIdTest() {
        // TODO: test subscriptionId
    }

    /**
     * Test the property 'subscriptionUniqueID'
     */
    @Test
    public void subscriptionUniqueIDTest() {
        // TODO: test subscriptionUniqueID
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'customerUniqueId'
     */
    @Test
    public void customerUniqueIdTest() {
        // TODO: test customerUniqueId
    }

    /**
     * Test the property 'customerEmail'
     */
    @Test
    public void customerEmailTest() {
        // TODO: test customerEmail
    }

    /**
     * Test the property 'customerFullname'
     */
    @Test
    public void customerFullnameTest() {
        // TODO: test customerFullname
    }

    /**
     * Test the property 'planId'
     */
    @Test
    public void planIdTest() {
        // TODO: test planId
    }

    /**
     * Test the property 'planName'
     */
    @Test
    public void planNameTest() {
        // TODO: test planName
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'productName'
     */
    @Test
    public void productNameTest() {
        // TODO: test productName
    }

    /**
     * Test the property 'createdOn'
     */
    @Test
    public void createdOnTest() {
        // TODO: test createdOn
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'isInFreeTrial'
     */
    @Test
    public void isInFreeTrialTest() {
        // TODO: test isInFreeTrial
    }

}
