/*
 * Billsby API
 * Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..
 *
 * The version of the OpenAPI document: 1.3.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * CustomerGetSubscriptionsByUniqueIdResponseInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CustomerGetSubscriptionsByUniqueIdResponseInner {
  public static final String SERIALIZED_NAME_SUBSCRIPTION_ID = "subscriptionId";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_ID)
  private String subscriptionId;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "productId";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  private Integer productId = 0;

  public static final String SERIALIZED_NAME_PRODUCT_NAME = "productName";
  @SerializedName(SERIALIZED_NAME_PRODUCT_NAME)
  private String productName;

  public static final String SERIALIZED_NAME_PLAN_ID = "planId";
  @SerializedName(SERIALIZED_NAME_PLAN_ID)
  private Integer planId = 0;

  public static final String SERIALIZED_NAME_PLAN_NAME = "planName";
  @SerializedName(SERIALIZED_NAME_PLAN_NAME)
  private String planName;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_REVENUE = "revenue";
  @SerializedName(SERIALIZED_NAME_REVENUE)
  private String revenue;

  public static final String SERIALIZED_NAME_NEXT_BILLING = "nextBilling";
  @SerializedName(SERIALIZED_NAME_NEXT_BILLING)
  private String nextBilling;

  public static final String SERIALIZED_NAME_CREATED_ON = "createdOn";
  @SerializedName(SERIALIZED_NAME_CREATED_ON)
  private String createdOn;

  public static final String SERIALIZED_NAME_UNITS = "units";
  @SerializedName(SERIALIZED_NAME_UNITS)
  private Integer units = 0;

  public CustomerGetSubscriptionsByUniqueIdResponseInner() {
  }

  public CustomerGetSubscriptionsByUniqueIdResponseInner subscriptionId(String subscriptionId) {
    
    
    
    
    this.subscriptionId = subscriptionId;
    return this;
  }

   /**
   * Get subscriptionId
   * @return subscriptionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getSubscriptionId() {
    return subscriptionId;
  }


  public void setSubscriptionId(String subscriptionId) {
    
    
    
    this.subscriptionId = subscriptionId;
  }


  public CustomerGetSubscriptionsByUniqueIdResponseInner productId(Integer productId) {
    
    
    
    
    this.productId = productId;
    return this;
  }

   /**
   * Get productId
   * @return productId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getProductId() {
    return productId;
  }


  public void setProductId(Integer productId) {
    
    
    
    this.productId = productId;
  }


  public CustomerGetSubscriptionsByUniqueIdResponseInner productName(String productName) {
    
    
    
    
    this.productName = productName;
    return this;
  }

   /**
   * Get productName
   * @return productName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getProductName() {
    return productName;
  }


  public void setProductName(String productName) {
    
    
    
    this.productName = productName;
  }


  public CustomerGetSubscriptionsByUniqueIdResponseInner planId(Integer planId) {
    
    
    
    
    this.planId = planId;
    return this;
  }

   /**
   * Get planId
   * @return planId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getPlanId() {
    return planId;
  }


  public void setPlanId(Integer planId) {
    
    
    
    this.planId = planId;
  }


  public CustomerGetSubscriptionsByUniqueIdResponseInner planName(String planName) {
    
    
    
    
    this.planName = planName;
    return this;
  }

   /**
   * Get planName
   * @return planName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getPlanName() {
    return planName;
  }


  public void setPlanName(String planName) {
    
    
    
    this.planName = planName;
  }


  public CustomerGetSubscriptionsByUniqueIdResponseInner status(String status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    
    
    
    this.status = status;
  }


  public CustomerGetSubscriptionsByUniqueIdResponseInner currency(String currency) {
    
    
    
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    
    
    
    this.currency = currency;
  }


  public CustomerGetSubscriptionsByUniqueIdResponseInner revenue(String revenue) {
    
    
    
    
    this.revenue = revenue;
    return this;
  }

   /**
   * Get revenue
   * @return revenue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getRevenue() {
    return revenue;
  }


  public void setRevenue(String revenue) {
    
    
    
    this.revenue = revenue;
  }


  public CustomerGetSubscriptionsByUniqueIdResponseInner nextBilling(String nextBilling) {
    
    
    
    
    this.nextBilling = nextBilling;
    return this;
  }

   /**
   * Get nextBilling
   * @return nextBilling
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-04-29T10:46:39.498Z", value = "")

  public String getNextBilling() {
    return nextBilling;
  }


  public void setNextBilling(String nextBilling) {
    
    
    
    this.nextBilling = nextBilling;
  }


  public CustomerGetSubscriptionsByUniqueIdResponseInner createdOn(String createdOn) {
    
    
    
    
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-04-29T10:46:39.498Z", value = "")

  public String getCreatedOn() {
    return createdOn;
  }


  public void setCreatedOn(String createdOn) {
    
    
    
    this.createdOn = createdOn;
  }


  public CustomerGetSubscriptionsByUniqueIdResponseInner units(Integer units) {
    
    
    
    
    this.units = units;
    return this;
  }

   /**
   * Get units
   * @return units
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getUnits() {
    return units;
  }


  public void setUnits(Integer units) {
    
    
    
    this.units = units;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CustomerGetSubscriptionsByUniqueIdResponseInner instance itself
   */
  public CustomerGetSubscriptionsByUniqueIdResponseInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerGetSubscriptionsByUniqueIdResponseInner customerGetSubscriptionsByUniqueIdResponseInner = (CustomerGetSubscriptionsByUniqueIdResponseInner) o;
    return Objects.equals(this.subscriptionId, customerGetSubscriptionsByUniqueIdResponseInner.subscriptionId) &&
        Objects.equals(this.productId, customerGetSubscriptionsByUniqueIdResponseInner.productId) &&
        Objects.equals(this.productName, customerGetSubscriptionsByUniqueIdResponseInner.productName) &&
        Objects.equals(this.planId, customerGetSubscriptionsByUniqueIdResponseInner.planId) &&
        Objects.equals(this.planName, customerGetSubscriptionsByUniqueIdResponseInner.planName) &&
        Objects.equals(this.status, customerGetSubscriptionsByUniqueIdResponseInner.status) &&
        Objects.equals(this.currency, customerGetSubscriptionsByUniqueIdResponseInner.currency) &&
        Objects.equals(this.revenue, customerGetSubscriptionsByUniqueIdResponseInner.revenue) &&
        Objects.equals(this.nextBilling, customerGetSubscriptionsByUniqueIdResponseInner.nextBilling) &&
        Objects.equals(this.createdOn, customerGetSubscriptionsByUniqueIdResponseInner.createdOn) &&
        Objects.equals(this.units, customerGetSubscriptionsByUniqueIdResponseInner.units)&&
        Objects.equals(this.additionalProperties, customerGetSubscriptionsByUniqueIdResponseInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subscriptionId, productId, productName, planId, planName, status, currency, revenue, nextBilling, createdOn, units, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerGetSubscriptionsByUniqueIdResponseInner {\n");
    sb.append("    subscriptionId: ").append(toIndentedString(subscriptionId)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    planName: ").append(toIndentedString(planName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    revenue: ").append(toIndentedString(revenue)).append("\n");
    sb.append("    nextBilling: ").append(toIndentedString(nextBilling)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("subscriptionId");
    openapiFields.add("productId");
    openapiFields.add("productName");
    openapiFields.add("planId");
    openapiFields.add("planName");
    openapiFields.add("status");
    openapiFields.add("currency");
    openapiFields.add("revenue");
    openapiFields.add("nextBilling");
    openapiFields.add("createdOn");
    openapiFields.add("units");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CustomerGetSubscriptionsByUniqueIdResponseInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CustomerGetSubscriptionsByUniqueIdResponseInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CustomerGetSubscriptionsByUniqueIdResponseInner is not found in the empty JSON string", CustomerGetSubscriptionsByUniqueIdResponseInner.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("subscriptionId") != null && !jsonObj.get("subscriptionId").isJsonNull()) && !jsonObj.get("subscriptionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subscriptionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subscriptionId").toString()));
      }
      if ((jsonObj.get("productName") != null && !jsonObj.get("productName").isJsonNull()) && !jsonObj.get("productName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productName").toString()));
      }
      if ((jsonObj.get("planName") != null && !jsonObj.get("planName").isJsonNull()) && !jsonObj.get("planName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `planName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("planName").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull()) && !jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      if ((jsonObj.get("revenue") != null && !jsonObj.get("revenue").isJsonNull()) && !jsonObj.get("revenue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `revenue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("revenue").toString()));
      }
      if ((jsonObj.get("nextBilling") != null && !jsonObj.get("nextBilling").isJsonNull()) && !jsonObj.get("nextBilling").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nextBilling` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nextBilling").toString()));
      }
      if ((jsonObj.get("createdOn") != null && !jsonObj.get("createdOn").isJsonNull()) && !jsonObj.get("createdOn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdOn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdOn").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CustomerGetSubscriptionsByUniqueIdResponseInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CustomerGetSubscriptionsByUniqueIdResponseInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CustomerGetSubscriptionsByUniqueIdResponseInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CustomerGetSubscriptionsByUniqueIdResponseInner.class));

       return (TypeAdapter<T>) new TypeAdapter<CustomerGetSubscriptionsByUniqueIdResponseInner>() {
           @Override
           public void write(JsonWriter out, CustomerGetSubscriptionsByUniqueIdResponseInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CustomerGetSubscriptionsByUniqueIdResponseInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CustomerGetSubscriptionsByUniqueIdResponseInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CustomerGetSubscriptionsByUniqueIdResponseInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CustomerGetSubscriptionsByUniqueIdResponseInner
  * @throws IOException if the JSON string is invalid with respect to CustomerGetSubscriptionsByUniqueIdResponseInner
  */
  public static CustomerGetSubscriptionsByUniqueIdResponseInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CustomerGetSubscriptionsByUniqueIdResponseInner.class);
  }

 /**
  * Convert an instance of CustomerGetSubscriptionsByUniqueIdResponseInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

