/*
 * Billsby API
 * Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..
 *
 * The version of the OpenAPI document: 1.3.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InvoiceDetailsResponseSubscriptionsInnerSubscriptionItemsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * InvoiceDetailsResponseSubscriptionsInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class InvoiceDetailsResponseSubscriptionsInner {
  public static final String SERIALIZED_NAME_SUBSCRIPTION_UNIQUE_ID = "subscriptionUniqueId";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_UNIQUE_ID)
  private String subscriptionUniqueId;

  public static final String SERIALIZED_NAME_PLAN_NAME = "planName";
  @SerializedName(SERIALIZED_NAME_PLAN_NAME)
  private String planName;

  public static final String SERIALIZED_NAME_BILLING_PERIOD_START = "billingPeriodStart";
  @SerializedName(SERIALIZED_NAME_BILLING_PERIOD_START)
  private String billingPeriodStart;

  public static final String SERIALIZED_NAME_BILLING_PERIOD_END = "billingPeriodEnd";
  @SerializedName(SERIALIZED_NAME_BILLING_PERIOD_END)
  private String billingPeriodEnd;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_ITEMS = "subscriptionItems";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_ITEMS)
  private List<InvoiceDetailsResponseSubscriptionsInnerSubscriptionItemsInner> subscriptionItems = null;

  public InvoiceDetailsResponseSubscriptionsInner() {
  }

  public InvoiceDetailsResponseSubscriptionsInner subscriptionUniqueId(String subscriptionUniqueId) {
    
    
    
    
    this.subscriptionUniqueId = subscriptionUniqueId;
    return this;
  }

   /**
   * Get subscriptionUniqueId
   * @return subscriptionUniqueId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Y4EDK80W71", value = "")

  public String getSubscriptionUniqueId() {
    return subscriptionUniqueId;
  }


  public void setSubscriptionUniqueId(String subscriptionUniqueId) {
    
    
    
    this.subscriptionUniqueId = subscriptionUniqueId;
  }


  public InvoiceDetailsResponseSubscriptionsInner planName(String planName) {
    
    
    
    
    this.planName = planName;
    return this;
  }

   /**
   * Get planName
   * @return planName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "premium", value = "")

  public String getPlanName() {
    return planName;
  }


  public void setPlanName(String planName) {
    
    
    
    this.planName = planName;
  }


  public InvoiceDetailsResponseSubscriptionsInner billingPeriodStart(String billingPeriodStart) {
    
    
    
    
    this.billingPeriodStart = billingPeriodStart;
    return this;
  }

   /**
   * Get billingPeriodStart
   * @return billingPeriodStart
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-04-29T00:14:57.297Z", value = "")

  public String getBillingPeriodStart() {
    return billingPeriodStart;
  }


  public void setBillingPeriodStart(String billingPeriodStart) {
    
    
    
    this.billingPeriodStart = billingPeriodStart;
  }


  public InvoiceDetailsResponseSubscriptionsInner billingPeriodEnd(String billingPeriodEnd) {
    
    
    
    
    this.billingPeriodEnd = billingPeriodEnd;
    return this;
  }

   /**
   * Get billingPeriodEnd
   * @return billingPeriodEnd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-04-29T00:14:57.297Z", value = "")

  public String getBillingPeriodEnd() {
    return billingPeriodEnd;
  }


  public void setBillingPeriodEnd(String billingPeriodEnd) {
    
    
    
    this.billingPeriodEnd = billingPeriodEnd;
  }


  public InvoiceDetailsResponseSubscriptionsInner subscriptionItems(List<InvoiceDetailsResponseSubscriptionsInnerSubscriptionItemsInner> subscriptionItems) {
    
    
    
    
    this.subscriptionItems = subscriptionItems;
    return this;
  }

  public InvoiceDetailsResponseSubscriptionsInner addSubscriptionItemsItem(InvoiceDetailsResponseSubscriptionsInnerSubscriptionItemsInner subscriptionItemsItem) {
    if (this.subscriptionItems == null) {
      this.subscriptionItems = new ArrayList<>();
    }
    this.subscriptionItems.add(subscriptionItemsItem);
    return this;
  }

   /**
   * Get subscriptionItems
   * @return subscriptionItems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<InvoiceDetailsResponseSubscriptionsInnerSubscriptionItemsInner> getSubscriptionItems() {
    return subscriptionItems;
  }


  public void setSubscriptionItems(List<InvoiceDetailsResponseSubscriptionsInnerSubscriptionItemsInner> subscriptionItems) {
    
    
    
    this.subscriptionItems = subscriptionItems;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the InvoiceDetailsResponseSubscriptionsInner instance itself
   */
  public InvoiceDetailsResponseSubscriptionsInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoiceDetailsResponseSubscriptionsInner invoiceDetailsResponseSubscriptionsInner = (InvoiceDetailsResponseSubscriptionsInner) o;
    return Objects.equals(this.subscriptionUniqueId, invoiceDetailsResponseSubscriptionsInner.subscriptionUniqueId) &&
        Objects.equals(this.planName, invoiceDetailsResponseSubscriptionsInner.planName) &&
        Objects.equals(this.billingPeriodStart, invoiceDetailsResponseSubscriptionsInner.billingPeriodStart) &&
        Objects.equals(this.billingPeriodEnd, invoiceDetailsResponseSubscriptionsInner.billingPeriodEnd) &&
        Objects.equals(this.subscriptionItems, invoiceDetailsResponseSubscriptionsInner.subscriptionItems)&&
        Objects.equals(this.additionalProperties, invoiceDetailsResponseSubscriptionsInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subscriptionUniqueId, planName, billingPeriodStart, billingPeriodEnd, subscriptionItems, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoiceDetailsResponseSubscriptionsInner {\n");
    sb.append("    subscriptionUniqueId: ").append(toIndentedString(subscriptionUniqueId)).append("\n");
    sb.append("    planName: ").append(toIndentedString(planName)).append("\n");
    sb.append("    billingPeriodStart: ").append(toIndentedString(billingPeriodStart)).append("\n");
    sb.append("    billingPeriodEnd: ").append(toIndentedString(billingPeriodEnd)).append("\n");
    sb.append("    subscriptionItems: ").append(toIndentedString(subscriptionItems)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("subscriptionUniqueId");
    openapiFields.add("planName");
    openapiFields.add("billingPeriodStart");
    openapiFields.add("billingPeriodEnd");
    openapiFields.add("subscriptionItems");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to InvoiceDetailsResponseSubscriptionsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!InvoiceDetailsResponseSubscriptionsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InvoiceDetailsResponseSubscriptionsInner is not found in the empty JSON string", InvoiceDetailsResponseSubscriptionsInner.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("subscriptionUniqueId") != null && !jsonObj.get("subscriptionUniqueId").isJsonNull()) && !jsonObj.get("subscriptionUniqueId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subscriptionUniqueId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subscriptionUniqueId").toString()));
      }
      if ((jsonObj.get("planName") != null && !jsonObj.get("planName").isJsonNull()) && !jsonObj.get("planName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `planName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("planName").toString()));
      }
      if ((jsonObj.get("billingPeriodStart") != null && !jsonObj.get("billingPeriodStart").isJsonNull()) && !jsonObj.get("billingPeriodStart").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `billingPeriodStart` to be a primitive type in the JSON string but got `%s`", jsonObj.get("billingPeriodStart").toString()));
      }
      if ((jsonObj.get("billingPeriodEnd") != null && !jsonObj.get("billingPeriodEnd").isJsonNull()) && !jsonObj.get("billingPeriodEnd").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `billingPeriodEnd` to be a primitive type in the JSON string but got `%s`", jsonObj.get("billingPeriodEnd").toString()));
      }
      if (jsonObj.get("subscriptionItems") != null && !jsonObj.get("subscriptionItems").isJsonNull()) {
        JsonArray jsonArraysubscriptionItems = jsonObj.getAsJsonArray("subscriptionItems");
        if (jsonArraysubscriptionItems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("subscriptionItems").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `subscriptionItems` to be an array in the JSON string but got `%s`", jsonObj.get("subscriptionItems").toString()));
          }

          // validate the optional field `subscriptionItems` (array)
          for (int i = 0; i < jsonArraysubscriptionItems.size(); i++) {
            InvoiceDetailsResponseSubscriptionsInnerSubscriptionItemsInner.validateJsonObject(jsonArraysubscriptionItems.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InvoiceDetailsResponseSubscriptionsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InvoiceDetailsResponseSubscriptionsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InvoiceDetailsResponseSubscriptionsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InvoiceDetailsResponseSubscriptionsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<InvoiceDetailsResponseSubscriptionsInner>() {
           @Override
           public void write(JsonWriter out, InvoiceDetailsResponseSubscriptionsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public InvoiceDetailsResponseSubscriptionsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             InvoiceDetailsResponseSubscriptionsInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InvoiceDetailsResponseSubscriptionsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InvoiceDetailsResponseSubscriptionsInner
  * @throws IOException if the JSON string is invalid with respect to InvoiceDetailsResponseSubscriptionsInner
  */
  public static InvoiceDetailsResponseSubscriptionsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InvoiceDetailsResponseSubscriptionsInner.class);
  }

 /**
  * Convert an instance of InvoiceDetailsResponseSubscriptionsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

