/*
 * Billsby API
 * Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..
 *
 * The version of the OpenAPI document: 1.3.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ProductUpdatePlanAndCycleRequestCyclesTiers;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Define your cycles
 */
@ApiModel(description = "Define your cycles")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ProductUpdatePlanAndCycleRequestCycles {
  public static final String SERIALIZED_NAME_CYCLE_ID = "cycleId";
  @SerializedName(SERIALIZED_NAME_CYCLE_ID)
  private Integer cycleId;

  public static final String SERIALIZED_NAME_FREQUENCY = "frequency";
  @SerializedName(SERIALIZED_NAME_FREQUENCY)
  private Integer frequency;

  public static final String SERIALIZED_NAME_FREQUENCY_TYPE = "frequencyType";
  @SerializedName(SERIALIZED_NAME_FREQUENCY_TYPE)
  private Integer frequencyType;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private Integer price;

  public static final String SERIALIZED_NAME_FREE_TRIAL = "freeTrial";
  @SerializedName(SERIALIZED_NAME_FREE_TRIAL)
  private Integer freeTrial;

  public static final String SERIALIZED_NAME_FREE_TRIAL_FREQUENCY_TYPE = "freeTrialFrequencyType";
  @SerializedName(SERIALIZED_NAME_FREE_TRIAL_FREQUENCY_TYPE)
  private Integer freeTrialFrequencyType;

  public static final String SERIALIZED_NAME_SETUP_FEE_PRICE = "setupFeePrice";
  @SerializedName(SERIALIZED_NAME_SETUP_FEE_PRICE)
  private Integer setupFeePrice;

  public static final String SERIALIZED_NAME_FREE_QUANTITY = "freeQuantity";
  @SerializedName(SERIALIZED_NAME_FREE_QUANTITY)
  private Integer freeQuantity;

  public static final String SERIALIZED_NAME_BILLING_DATE_TYPE = "billingDateType";
  @SerializedName(SERIALIZED_NAME_BILLING_DATE_TYPE)
  private Integer billingDateType;

  public static final String SERIALIZED_NAME_FIXED_BILLING_DATE_DAY = "fixedBillingDateDay";
  @SerializedName(SERIALIZED_NAME_FIXED_BILLING_DATE_DAY)
  private Integer fixedBillingDateDay;

  public static final String SERIALIZED_NAME_PRO_RATE_OPTION = "proRateOption";
  @SerializedName(SERIALIZED_NAME_PRO_RATE_OPTION)
  private Integer proRateOption;

  public static final String SERIALIZED_NAME_VISIBILITY = "visibility";
  @SerializedName(SERIALIZED_NAME_VISIBILITY)
  private Integer visibility;

  public static final String SERIALIZED_NAME_TIERS = "tiers";
  @SerializedName(SERIALIZED_NAME_TIERS)
  private ProductUpdatePlanAndCycleRequestCyclesTiers tiers;

  public ProductUpdatePlanAndCycleRequestCycles() {
  }

  public ProductUpdatePlanAndCycleRequestCycles cycleId(Integer cycleId) {
    
    
    
    
    this.cycleId = cycleId;
    return this;
  }

   /**
   * The unique identifier of the cycle in the Billsby platform
   * @return cycleId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique identifier of the cycle in the Billsby platform")

  public Integer getCycleId() {
    return cycleId;
  }


  public void setCycleId(Integer cycleId) {
    
    
    
    this.cycleId = cycleId;
  }


  public ProductUpdatePlanAndCycleRequestCycles frequency(Integer frequency) {
    
    
    
    
    this.frequency = frequency;
    return this;
  }

   /**
   * A number with the update frequency (for example: 5 to renew every five of frequencyType)
   * @return frequency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A number with the update frequency (for example: 5 to renew every five of frequencyType)")

  public Integer getFrequency() {
    return frequency;
  }


  public void setFrequency(Integer frequency) {
    
    
    
    this.frequency = frequency;
  }


  public ProductUpdatePlanAndCycleRequestCycles frequencyType(Integer frequencyType) {
    
    
    
    
    this.frequencyType = frequencyType;
    return this;
  }

   /**
   * Daily &#x3D; 1, Weekly &#x3D; 2, Monthly &#x3D; 3, Yearly &#x3D; 4
   * @return frequencyType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Daily = 1, Weekly = 2, Monthly = 3, Yearly = 4")

  public Integer getFrequencyType() {
    return frequencyType;
  }


  public void setFrequencyType(Integer frequencyType) {
    
    
    
    this.frequencyType = frequencyType;
  }


  public ProductUpdatePlanAndCycleRequestCycles price(Integer price) {
    
    
    
    
    this.price = price;
    return this;
  }

   /**
   * The price amount of this cycle (unused in tiered based cycles)
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The price amount of this cycle (unused in tiered based cycles)")

  public Integer getPrice() {
    return price;
  }


  public void setPrice(Integer price) {
    
    
    
    this.price = price;
  }


  public ProductUpdatePlanAndCycleRequestCycles freeTrial(Integer freeTrial) {
    
    
    
    
    this.freeTrial = freeTrial;
    return this;
  }

   /**
   * A number with the amount of free trial (for example: 5 for five of frequencyType of free trial)
   * @return freeTrial
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A number with the amount of free trial (for example: 5 for five of frequencyType of free trial)")

  public Integer getFreeTrial() {
    return freeTrial;
  }


  public void setFreeTrial(Integer freeTrial) {
    
    
    
    this.freeTrial = freeTrial;
  }


  public ProductUpdatePlanAndCycleRequestCycles freeTrialFrequencyType(Integer freeTrialFrequencyType) {
    
    
    
    
    this.freeTrialFrequencyType = freeTrialFrequencyType;
    return this;
  }

   /**
   * Daily &#x3D; 1, Weekly &#x3D; 2, Monthly &#x3D; 3, Yearly &#x3D; 4
   * @return freeTrialFrequencyType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Daily = 1, Weekly = 2, Monthly = 3, Yearly = 4")

  public Integer getFreeTrialFrequencyType() {
    return freeTrialFrequencyType;
  }


  public void setFreeTrialFrequencyType(Integer freeTrialFrequencyType) {
    
    
    
    this.freeTrialFrequencyType = freeTrialFrequencyType;
  }


  public ProductUpdatePlanAndCycleRequestCycles setupFeePrice(Integer setupFeePrice) {
    
    
    
    
    this.setupFeePrice = setupFeePrice;
    return this;
  }

   /**
   * The price amount of setup fee (charged only on first invoice of new subscriptions)
   * @return setupFeePrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The price amount of setup fee (charged only on first invoice of new subscriptions)")

  public Integer getSetupFeePrice() {
    return setupFeePrice;
  }


  public void setSetupFeePrice(Integer setupFeePrice) {
    
    
    
    this.setupFeePrice = setupFeePrice;
  }


  public ProductUpdatePlanAndCycleRequestCycles freeQuantity(Integer freeQuantity) {
    
    
    
    
    this.freeQuantity = freeQuantity;
    return this;
  }

   /**
   * The amount of free units in tiered based cycles
   * @return freeQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The amount of free units in tiered based cycles")

  public Integer getFreeQuantity() {
    return freeQuantity;
  }


  public void setFreeQuantity(Integer freeQuantity) {
    
    
    
    this.freeQuantity = freeQuantity;
  }


  public ProductUpdatePlanAndCycleRequestCycles billingDateType(Integer billingDateType) {
    
    
    
    
    this.billingDateType = billingDateType;
    return this;
  }

   /**
   * Anniversary &#x3D; 1, FixedDayEachMonth &#x3D; 2, FixedDayOfTheWeek &#x3D; 3
   * @return billingDateType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Anniversary = 1, FixedDayEachMonth = 2, FixedDayOfTheWeek = 3")

  public Integer getBillingDateType() {
    return billingDateType;
  }


  public void setBillingDateType(Integer billingDateType) {
    
    
    
    this.billingDateType = billingDateType;
  }


  public ProductUpdatePlanAndCycleRequestCycles fixedBillingDateDay(Integer fixedBillingDateDay) {
    
    
    
    
    this.fixedBillingDateDay = fixedBillingDateDay;
    return this;
  }

   /**
   * The fixed billing date if there is one (from 1 to 28)
   * @return fixedBillingDateDay
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The fixed billing date if there is one (from 1 to 28)")

  public Integer getFixedBillingDateDay() {
    return fixedBillingDateDay;
  }


  public void setFixedBillingDateDay(Integer fixedBillingDateDay) {
    
    
    
    this.fixedBillingDateDay = fixedBillingDateDay;
  }


  public ProductUpdatePlanAndCycleRequestCycles proRateOption(Integer proRateOption) {
    
    
    
    
    this.proRateOption = proRateOption;
    return this;
  }

   /**
   * DoNotProRate &#x3D; 1, DoNotChargeUntilNextCycle &#x3D; 2, ProRateBasedOnDaysRemaining &#x3D; 3
   * @return proRateOption
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "DoNotProRate = 1, DoNotChargeUntilNextCycle = 2, ProRateBasedOnDaysRemaining = 3")

  public Integer getProRateOption() {
    return proRateOption;
  }


  public void setProRateOption(Integer proRateOption) {
    
    
    
    this.proRateOption = proRateOption;
  }


  public ProductUpdatePlanAndCycleRequestCycles visibility(Integer visibility) {
    
    
    
    
    this.visibility = visibility;
    return this;
  }

   /**
   * The type of visibility of each product; public, hidden and on-sale. Available values: 0, 1, 2, 3 (Public&#x3D;0, Hidden&#x3D;1, Internal&#x3D;2, OffSale&#x3D;3)
   * @return visibility
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of visibility of each product; public, hidden and on-sale. Available values: 0, 1, 2, 3 (Public=0, Hidden=1, Internal=2, OffSale=3)")

  public Integer getVisibility() {
    return visibility;
  }


  public void setVisibility(Integer visibility) {
    
    
    
    this.visibility = visibility;
  }


  public ProductUpdatePlanAndCycleRequestCycles tiers(ProductUpdatePlanAndCycleRequestCyclesTiers tiers) {
    
    
    
    
    this.tiers = tiers;
    return this;
  }

   /**
   * Get tiers
   * @return tiers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProductUpdatePlanAndCycleRequestCyclesTiers getTiers() {
    return tiers;
  }


  public void setTiers(ProductUpdatePlanAndCycleRequestCyclesTiers tiers) {
    
    
    
    this.tiers = tiers;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ProductUpdatePlanAndCycleRequestCycles instance itself
   */
  public ProductUpdatePlanAndCycleRequestCycles putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductUpdatePlanAndCycleRequestCycles productUpdatePlanAndCycleRequestCycles = (ProductUpdatePlanAndCycleRequestCycles) o;
    return Objects.equals(this.cycleId, productUpdatePlanAndCycleRequestCycles.cycleId) &&
        Objects.equals(this.frequency, productUpdatePlanAndCycleRequestCycles.frequency) &&
        Objects.equals(this.frequencyType, productUpdatePlanAndCycleRequestCycles.frequencyType) &&
        Objects.equals(this.price, productUpdatePlanAndCycleRequestCycles.price) &&
        Objects.equals(this.freeTrial, productUpdatePlanAndCycleRequestCycles.freeTrial) &&
        Objects.equals(this.freeTrialFrequencyType, productUpdatePlanAndCycleRequestCycles.freeTrialFrequencyType) &&
        Objects.equals(this.setupFeePrice, productUpdatePlanAndCycleRequestCycles.setupFeePrice) &&
        Objects.equals(this.freeQuantity, productUpdatePlanAndCycleRequestCycles.freeQuantity) &&
        Objects.equals(this.billingDateType, productUpdatePlanAndCycleRequestCycles.billingDateType) &&
        Objects.equals(this.fixedBillingDateDay, productUpdatePlanAndCycleRequestCycles.fixedBillingDateDay) &&
        Objects.equals(this.proRateOption, productUpdatePlanAndCycleRequestCycles.proRateOption) &&
        Objects.equals(this.visibility, productUpdatePlanAndCycleRequestCycles.visibility) &&
        Objects.equals(this.tiers, productUpdatePlanAndCycleRequestCycles.tiers)&&
        Objects.equals(this.additionalProperties, productUpdatePlanAndCycleRequestCycles.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cycleId, frequency, frequencyType, price, freeTrial, freeTrialFrequencyType, setupFeePrice, freeQuantity, billingDateType, fixedBillingDateDay, proRateOption, visibility, tiers, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductUpdatePlanAndCycleRequestCycles {\n");
    sb.append("    cycleId: ").append(toIndentedString(cycleId)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    frequencyType: ").append(toIndentedString(frequencyType)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    freeTrial: ").append(toIndentedString(freeTrial)).append("\n");
    sb.append("    freeTrialFrequencyType: ").append(toIndentedString(freeTrialFrequencyType)).append("\n");
    sb.append("    setupFeePrice: ").append(toIndentedString(setupFeePrice)).append("\n");
    sb.append("    freeQuantity: ").append(toIndentedString(freeQuantity)).append("\n");
    sb.append("    billingDateType: ").append(toIndentedString(billingDateType)).append("\n");
    sb.append("    fixedBillingDateDay: ").append(toIndentedString(fixedBillingDateDay)).append("\n");
    sb.append("    proRateOption: ").append(toIndentedString(proRateOption)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    tiers: ").append(toIndentedString(tiers)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cycleId");
    openapiFields.add("frequency");
    openapiFields.add("frequencyType");
    openapiFields.add("price");
    openapiFields.add("freeTrial");
    openapiFields.add("freeTrialFrequencyType");
    openapiFields.add("setupFeePrice");
    openapiFields.add("freeQuantity");
    openapiFields.add("billingDateType");
    openapiFields.add("fixedBillingDateDay");
    openapiFields.add("proRateOption");
    openapiFields.add("visibility");
    openapiFields.add("tiers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ProductUpdatePlanAndCycleRequestCycles
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ProductUpdatePlanAndCycleRequestCycles.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProductUpdatePlanAndCycleRequestCycles is not found in the empty JSON string", ProductUpdatePlanAndCycleRequestCycles.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `tiers`
      if (jsonObj.get("tiers") != null && !jsonObj.get("tiers").isJsonNull()) {
        ProductUpdatePlanAndCycleRequestCyclesTiers.validateJsonObject(jsonObj.getAsJsonObject("tiers"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProductUpdatePlanAndCycleRequestCycles.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProductUpdatePlanAndCycleRequestCycles' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProductUpdatePlanAndCycleRequestCycles> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProductUpdatePlanAndCycleRequestCycles.class));

       return (TypeAdapter<T>) new TypeAdapter<ProductUpdatePlanAndCycleRequestCycles>() {
           @Override
           public void write(JsonWriter out, ProductUpdatePlanAndCycleRequestCycles value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ProductUpdatePlanAndCycleRequestCycles read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ProductUpdatePlanAndCycleRequestCycles instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProductUpdatePlanAndCycleRequestCycles given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProductUpdatePlanAndCycleRequestCycles
  * @throws IOException if the JSON string is invalid with respect to ProductUpdatePlanAndCycleRequestCycles
  */
  public static ProductUpdatePlanAndCycleRequestCycles fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProductUpdatePlanAndCycleRequestCycles.class);
  }

 /**
  * Convert an instance of ProductUpdatePlanAndCycleRequestCycles to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

