/*
 * Billsby API
 * Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.  Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.      Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.  If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build.   Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..
 *
 * The version of the OpenAPI document: 1.3.5
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ProductListProductsResponseResultsInnerCustomFieldsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ProductListProductsResponseResultsInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ProductListProductsResponseResultsInner {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "productId";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  private Integer productId = 0;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_VISIBILITY = "visibility";
  @SerializedName(SERIALIZED_NAME_VISIBILITY)
  private Integer visibility = 0;

  public static final String SERIALIZED_NAME_BILLING_CURRENCY = "billingCurrency";
  @SerializedName(SERIALIZED_NAME_BILLING_CURRENCY)
  private String billingCurrency;

  public static final String SERIALIZED_NAME_BILLING_CURRENCY_TEMPLATE = "billingCurrencyTemplate";
  @SerializedName(SERIALIZED_NAME_BILLING_CURRENCY_TEMPLATE)
  private String billingCurrencyTemplate;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_TYPE_OF_PRODUCT = "typeOfProduct";
  @SerializedName(SERIALIZED_NAME_TYPE_OF_PRODUCT)
  private Integer typeOfProduct = 0;

  public static final String SERIALIZED_NAME_HAS_PLANS = "hasPlans";
  @SerializedName(SERIALIZED_NAME_HAS_PLANS)
  private Boolean hasPlans = true;

  public static final String SERIALIZED_NAME_IS_SHIPPING_ADDRESS_REQUIRED = "isShippingAddressRequired";
  @SerializedName(SERIALIZED_NAME_IS_SHIPPING_ADDRESS_REQUIRED)
  private Boolean isShippingAddressRequired = true;

  public static final String SERIALIZED_NAME_IS_SHIPPING_ADDRESS_VALIDATION_REQUIRED = "isShippingAddressValidationRequired";
  @SerializedName(SERIALIZED_NAME_IS_SHIPPING_ADDRESS_VALIDATION_REQUIRED)
  private Boolean isShippingAddressValidationRequired = true;

  public static final String SERIALIZED_NAME_IS_BILLING_ADDRESS_VALIDATION_REQUIRED = "isBillingAddressValidationRequired";
  @SerializedName(SERIALIZED_NAME_IS_BILLING_ADDRESS_VALIDATION_REQUIRED)
  private Boolean isBillingAddressValidationRequired = true;

  public static final String SERIALIZED_NAME_IS_ADDITIONAL_EMAIL_REQUIRED = "isAdditionalEmailRequired";
  @SerializedName(SERIALIZED_NAME_IS_ADDITIONAL_EMAIL_REQUIRED)
  private Boolean isAdditionalEmailRequired = true;

  public static final String SERIALIZED_NAME_IS_PHONE_NUMBER_REQUIRED = "isPhoneNumberRequired";
  @SerializedName(SERIALIZED_NAME_IS_PHONE_NUMBER_REQUIRED)
  private Boolean isPhoneNumberRequired = true;

  public static final String SERIALIZED_NAME_IS_MARKETING_CONSENT_REQUIRED = "isMarketingConsentRequired";
  @SerializedName(SERIALIZED_NAME_IS_MARKETING_CONSENT_REQUIRED)
  private Boolean isMarketingConsentRequired = true;

  public static final String SERIALIZED_NAME_NUMBER_OF_PLANS = "numberOfPlans";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_PLANS)
  private Integer numberOfPlans = 0;

  public static final String SERIALIZED_NAME_ALERT_EMAIL = "alertEmail";
  @SerializedName(SERIALIZED_NAME_ALERT_EMAIL)
  private String alertEmail;

  public static final String SERIALIZED_NAME_CUSTOM_FIELDS = "customFields";
  @SerializedName(SERIALIZED_NAME_CUSTOM_FIELDS)
  private List<ProductListProductsResponseResultsInnerCustomFieldsInner> customFields = null;

  public static final String SERIALIZED_NAME_ORDERED_CUSTOM_FIELDS = "orderedCustomFields";
  @SerializedName(SERIALIZED_NAME_ORDERED_CUSTOM_FIELDS)
  private List<Integer> orderedCustomFields = null;

  public ProductListProductsResponseResultsInner() {
  }

  public ProductListProductsResponseResultsInner description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "A description of the product", value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public ProductListProductsResponseResultsInner productId(Integer productId) {
    
    
    
    
    this.productId = productId;
    return this;
  }

   /**
   * Get productId
   * @return productId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getProductId() {
    return productId;
  }


  public void setProductId(Integer productId) {
    
    
    
    this.productId = productId;
  }


  public ProductListProductsResponseResultsInner name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Product Name", value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public ProductListProductsResponseResultsInner visibility(Integer visibility) {
    
    
    
    
    this.visibility = visibility;
    return this;
  }

   /**
   * Get visibility
   * @return visibility
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getVisibility() {
    return visibility;
  }


  public void setVisibility(Integer visibility) {
    
    
    
    this.visibility = visibility;
  }


  public ProductListProductsResponseResultsInner billingCurrency(String billingCurrency) {
    
    
    
    
    this.billingCurrency = billingCurrency;
    return this;
  }

   /**
   * Get billingCurrency
   * @return billingCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "USD", value = "")

  public String getBillingCurrency() {
    return billingCurrency;
  }


  public void setBillingCurrency(String billingCurrency) {
    
    
    
    this.billingCurrency = billingCurrency;
  }


  public ProductListProductsResponseResultsInner billingCurrencyTemplate(String billingCurrencyTemplate) {
    
    
    
    
    this.billingCurrencyTemplate = billingCurrencyTemplate;
    return this;
  }

   /**
   * Get billingCurrencyTemplate
   * @return billingCurrencyTemplate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "$X.XX", value = "")

  public String getBillingCurrencyTemplate() {
    return billingCurrencyTemplate;
  }


  public void setBillingCurrencyTemplate(String billingCurrencyTemplate) {
    
    
    
    this.billingCurrencyTemplate = billingCurrencyTemplate;
  }


  public ProductListProductsResponseResultsInner displayName(String displayName) {
    
    
    
    
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Product Name", value = "")

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    
    
    
    this.displayName = displayName;
  }


  public ProductListProductsResponseResultsInner typeOfProduct(Integer typeOfProduct) {
    
    
    
    
    this.typeOfProduct = typeOfProduct;
    return this;
  }

   /**
   * Get typeOfProduct
   * @return typeOfProduct
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "")

  public Integer getTypeOfProduct() {
    return typeOfProduct;
  }


  public void setTypeOfProduct(Integer typeOfProduct) {
    
    
    
    this.typeOfProduct = typeOfProduct;
  }


  public ProductListProductsResponseResultsInner hasPlans(Boolean hasPlans) {
    
    
    
    
    this.hasPlans = hasPlans;
    return this;
  }

   /**
   * Get hasPlans
   * @return hasPlans
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getHasPlans() {
    return hasPlans;
  }


  public void setHasPlans(Boolean hasPlans) {
    
    
    
    this.hasPlans = hasPlans;
  }


  public ProductListProductsResponseResultsInner isShippingAddressRequired(Boolean isShippingAddressRequired) {
    
    
    
    
    this.isShippingAddressRequired = isShippingAddressRequired;
    return this;
  }

   /**
   * Get isShippingAddressRequired
   * @return isShippingAddressRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getIsShippingAddressRequired() {
    return isShippingAddressRequired;
  }


  public void setIsShippingAddressRequired(Boolean isShippingAddressRequired) {
    
    
    
    this.isShippingAddressRequired = isShippingAddressRequired;
  }


  public ProductListProductsResponseResultsInner isShippingAddressValidationRequired(Boolean isShippingAddressValidationRequired) {
    
    
    
    
    this.isShippingAddressValidationRequired = isShippingAddressValidationRequired;
    return this;
  }

   /**
   * Get isShippingAddressValidationRequired
   * @return isShippingAddressValidationRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getIsShippingAddressValidationRequired() {
    return isShippingAddressValidationRequired;
  }


  public void setIsShippingAddressValidationRequired(Boolean isShippingAddressValidationRequired) {
    
    
    
    this.isShippingAddressValidationRequired = isShippingAddressValidationRequired;
  }


  public ProductListProductsResponseResultsInner isBillingAddressValidationRequired(Boolean isBillingAddressValidationRequired) {
    
    
    
    
    this.isBillingAddressValidationRequired = isBillingAddressValidationRequired;
    return this;
  }

   /**
   * Get isBillingAddressValidationRequired
   * @return isBillingAddressValidationRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getIsBillingAddressValidationRequired() {
    return isBillingAddressValidationRequired;
  }


  public void setIsBillingAddressValidationRequired(Boolean isBillingAddressValidationRequired) {
    
    
    
    this.isBillingAddressValidationRequired = isBillingAddressValidationRequired;
  }


  public ProductListProductsResponseResultsInner isAdditionalEmailRequired(Boolean isAdditionalEmailRequired) {
    
    
    
    
    this.isAdditionalEmailRequired = isAdditionalEmailRequired;
    return this;
  }

   /**
   * Get isAdditionalEmailRequired
   * @return isAdditionalEmailRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getIsAdditionalEmailRequired() {
    return isAdditionalEmailRequired;
  }


  public void setIsAdditionalEmailRequired(Boolean isAdditionalEmailRequired) {
    
    
    
    this.isAdditionalEmailRequired = isAdditionalEmailRequired;
  }


  public ProductListProductsResponseResultsInner isPhoneNumberRequired(Boolean isPhoneNumberRequired) {
    
    
    
    
    this.isPhoneNumberRequired = isPhoneNumberRequired;
    return this;
  }

   /**
   * Get isPhoneNumberRequired
   * @return isPhoneNumberRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getIsPhoneNumberRequired() {
    return isPhoneNumberRequired;
  }


  public void setIsPhoneNumberRequired(Boolean isPhoneNumberRequired) {
    
    
    
    this.isPhoneNumberRequired = isPhoneNumberRequired;
  }


  public ProductListProductsResponseResultsInner isMarketingConsentRequired(Boolean isMarketingConsentRequired) {
    
    
    
    
    this.isMarketingConsentRequired = isMarketingConsentRequired;
    return this;
  }

   /**
   * Get isMarketingConsentRequired
   * @return isMarketingConsentRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getIsMarketingConsentRequired() {
    return isMarketingConsentRequired;
  }


  public void setIsMarketingConsentRequired(Boolean isMarketingConsentRequired) {
    
    
    
    this.isMarketingConsentRequired = isMarketingConsentRequired;
  }


  public ProductListProductsResponseResultsInner numberOfPlans(Integer numberOfPlans) {
    
    
    
    
    this.numberOfPlans = numberOfPlans;
    return this;
  }

   /**
   * Get numberOfPlans
   * @return numberOfPlans
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getNumberOfPlans() {
    return numberOfPlans;
  }


  public void setNumberOfPlans(Integer numberOfPlans) {
    
    
    
    this.numberOfPlans = numberOfPlans;
  }


  public ProductListProductsResponseResultsInner alertEmail(String alertEmail) {
    
    
    
    
    this.alertEmail = alertEmail;
    return this;
  }

   /**
   * Get alertEmail
   * @return alertEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getAlertEmail() {
    return alertEmail;
  }


  public void setAlertEmail(String alertEmail) {
    
    
    
    this.alertEmail = alertEmail;
  }


  public ProductListProductsResponseResultsInner customFields(List<ProductListProductsResponseResultsInnerCustomFieldsInner> customFields) {
    
    
    
    
    this.customFields = customFields;
    return this;
  }

  public ProductListProductsResponseResultsInner addCustomFieldsItem(ProductListProductsResponseResultsInnerCustomFieldsInner customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new ArrayList<>();
    }
    this.customFields.add(customFieldsItem);
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ProductListProductsResponseResultsInnerCustomFieldsInner> getCustomFields() {
    return customFields;
  }


  public void setCustomFields(List<ProductListProductsResponseResultsInnerCustomFieldsInner> customFields) {
    
    
    
    this.customFields = customFields;
  }


  public ProductListProductsResponseResultsInner orderedCustomFields(List<Integer> orderedCustomFields) {
    
    
    
    
    this.orderedCustomFields = orderedCustomFields;
    return this;
  }

  public ProductListProductsResponseResultsInner addOrderedCustomFieldsItem(Integer orderedCustomFieldsItem) {
    if (this.orderedCustomFields == null) {
      this.orderedCustomFields = new ArrayList<>();
    }
    this.orderedCustomFields.add(orderedCustomFieldsItem);
    return this;
  }

   /**
   * Get orderedCustomFields
   * @return orderedCustomFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getOrderedCustomFields() {
    return orderedCustomFields;
  }


  public void setOrderedCustomFields(List<Integer> orderedCustomFields) {
    
    
    
    this.orderedCustomFields = orderedCustomFields;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ProductListProductsResponseResultsInner instance itself
   */
  public ProductListProductsResponseResultsInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductListProductsResponseResultsInner productListProductsResponseResultsInner = (ProductListProductsResponseResultsInner) o;
    return Objects.equals(this.description, productListProductsResponseResultsInner.description) &&
        Objects.equals(this.productId, productListProductsResponseResultsInner.productId) &&
        Objects.equals(this.name, productListProductsResponseResultsInner.name) &&
        Objects.equals(this.visibility, productListProductsResponseResultsInner.visibility) &&
        Objects.equals(this.billingCurrency, productListProductsResponseResultsInner.billingCurrency) &&
        Objects.equals(this.billingCurrencyTemplate, productListProductsResponseResultsInner.billingCurrencyTemplate) &&
        Objects.equals(this.displayName, productListProductsResponseResultsInner.displayName) &&
        Objects.equals(this.typeOfProduct, productListProductsResponseResultsInner.typeOfProduct) &&
        Objects.equals(this.hasPlans, productListProductsResponseResultsInner.hasPlans) &&
        Objects.equals(this.isShippingAddressRequired, productListProductsResponseResultsInner.isShippingAddressRequired) &&
        Objects.equals(this.isShippingAddressValidationRequired, productListProductsResponseResultsInner.isShippingAddressValidationRequired) &&
        Objects.equals(this.isBillingAddressValidationRequired, productListProductsResponseResultsInner.isBillingAddressValidationRequired) &&
        Objects.equals(this.isAdditionalEmailRequired, productListProductsResponseResultsInner.isAdditionalEmailRequired) &&
        Objects.equals(this.isPhoneNumberRequired, productListProductsResponseResultsInner.isPhoneNumberRequired) &&
        Objects.equals(this.isMarketingConsentRequired, productListProductsResponseResultsInner.isMarketingConsentRequired) &&
        Objects.equals(this.numberOfPlans, productListProductsResponseResultsInner.numberOfPlans) &&
        Objects.equals(this.alertEmail, productListProductsResponseResultsInner.alertEmail) &&
        Objects.equals(this.customFields, productListProductsResponseResultsInner.customFields) &&
        Objects.equals(this.orderedCustomFields, productListProductsResponseResultsInner.orderedCustomFields)&&
        Objects.equals(this.additionalProperties, productListProductsResponseResultsInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, productId, name, visibility, billingCurrency, billingCurrencyTemplate, displayName, typeOfProduct, hasPlans, isShippingAddressRequired, isShippingAddressValidationRequired, isBillingAddressValidationRequired, isAdditionalEmailRequired, isPhoneNumberRequired, isMarketingConsentRequired, numberOfPlans, alertEmail, customFields, orderedCustomFields, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductListProductsResponseResultsInner {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    billingCurrency: ").append(toIndentedString(billingCurrency)).append("\n");
    sb.append("    billingCurrencyTemplate: ").append(toIndentedString(billingCurrencyTemplate)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    typeOfProduct: ").append(toIndentedString(typeOfProduct)).append("\n");
    sb.append("    hasPlans: ").append(toIndentedString(hasPlans)).append("\n");
    sb.append("    isShippingAddressRequired: ").append(toIndentedString(isShippingAddressRequired)).append("\n");
    sb.append("    isShippingAddressValidationRequired: ").append(toIndentedString(isShippingAddressValidationRequired)).append("\n");
    sb.append("    isBillingAddressValidationRequired: ").append(toIndentedString(isBillingAddressValidationRequired)).append("\n");
    sb.append("    isAdditionalEmailRequired: ").append(toIndentedString(isAdditionalEmailRequired)).append("\n");
    sb.append("    isPhoneNumberRequired: ").append(toIndentedString(isPhoneNumberRequired)).append("\n");
    sb.append("    isMarketingConsentRequired: ").append(toIndentedString(isMarketingConsentRequired)).append("\n");
    sb.append("    numberOfPlans: ").append(toIndentedString(numberOfPlans)).append("\n");
    sb.append("    alertEmail: ").append(toIndentedString(alertEmail)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    orderedCustomFields: ").append(toIndentedString(orderedCustomFields)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("productId");
    openapiFields.add("name");
    openapiFields.add("visibility");
    openapiFields.add("billingCurrency");
    openapiFields.add("billingCurrencyTemplate");
    openapiFields.add("displayName");
    openapiFields.add("typeOfProduct");
    openapiFields.add("hasPlans");
    openapiFields.add("isShippingAddressRequired");
    openapiFields.add("isShippingAddressValidationRequired");
    openapiFields.add("isBillingAddressValidationRequired");
    openapiFields.add("isAdditionalEmailRequired");
    openapiFields.add("isPhoneNumberRequired");
    openapiFields.add("isMarketingConsentRequired");
    openapiFields.add("numberOfPlans");
    openapiFields.add("alertEmail");
    openapiFields.add("customFields");
    openapiFields.add("orderedCustomFields");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ProductListProductsResponseResultsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ProductListProductsResponseResultsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProductListProductsResponseResultsInner is not found in the empty JSON string", ProductListProductsResponseResultsInner.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("billingCurrency") != null && !jsonObj.get("billingCurrency").isJsonNull()) && !jsonObj.get("billingCurrency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `billingCurrency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("billingCurrency").toString()));
      }
      if ((jsonObj.get("billingCurrencyTemplate") != null && !jsonObj.get("billingCurrencyTemplate").isJsonNull()) && !jsonObj.get("billingCurrencyTemplate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `billingCurrencyTemplate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("billingCurrencyTemplate").toString()));
      }
      if ((jsonObj.get("displayName") != null && !jsonObj.get("displayName").isJsonNull()) && !jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      if ((jsonObj.get("alertEmail") != null && !jsonObj.get("alertEmail").isJsonNull()) && !jsonObj.get("alertEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `alertEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alertEmail").toString()));
      }
      if (jsonObj.get("customFields") != null && !jsonObj.get("customFields").isJsonNull()) {
        JsonArray jsonArraycustomFields = jsonObj.getAsJsonArray("customFields");
        if (jsonArraycustomFields != null) {
          // ensure the json data is an array
          if (!jsonObj.get("customFields").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `customFields` to be an array in the JSON string but got `%s`", jsonObj.get("customFields").toString()));
          }

          // validate the optional field `customFields` (array)
          for (int i = 0; i < jsonArraycustomFields.size(); i++) {
            ProductListProductsResponseResultsInnerCustomFieldsInner.validateJsonObject(jsonArraycustomFields.get(i).getAsJsonObject());
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("orderedCustomFields") != null && !jsonObj.get("orderedCustomFields").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `orderedCustomFields` to be an array in the JSON string but got `%s`", jsonObj.get("orderedCustomFields").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProductListProductsResponseResultsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProductListProductsResponseResultsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProductListProductsResponseResultsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProductListProductsResponseResultsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ProductListProductsResponseResultsInner>() {
           @Override
           public void write(JsonWriter out, ProductListProductsResponseResultsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ProductListProductsResponseResultsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ProductListProductsResponseResultsInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProductListProductsResponseResultsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProductListProductsResponseResultsInner
  * @throws IOException if the JSON string is invalid with respect to ProductListProductsResponseResultsInner
  */
  public static ProductListProductsResponseResultsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProductListProductsResponseResultsInner.class);
  }

 /**
  * Convert an instance of ProductListProductsResponseResultsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

